image: gcc:10.3.0

default:
  # install dependencies
  before_script:
    - apt update
    - gcc --version
    # download and install miniconda
    - wget -nv https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh
    - bash miniconda3.sh -b -p ./miniconda3
    - export PATH="$PWD/miniconda3/bin:$PATH"
    - conda --version
    # create and activate environment
    - conda create -n pommer_build python=3.7
    - source $PWD/miniconda3/bin/activate pommer_build
    # install (some) dependencies via conda-forge
    - conda install -y -c conda-forge z5py xtensor boost nlohmann_json blosc catch2
    # now get libraries that are not in conda-forge
    - mkdir lib
    - cd lib
    # install blaze (and its dependencies)
    - apt -y install libblas-dev liblapack-dev
    - wget -nv https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.8.tar.gz
    - tar -xf blaze-3.8.tar.gz 
    # install PyTorch (CPU-only)
    - wget -nv https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip -O libtorch.zip
    - unzip -q libtorch.zip
    - bash ../fix_pytorch.sh ./libtorch
    # go back
    - cd ..

build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # install additional build requirements
    - apt -y install cmake
    # define environment variables
    - export BLAZE_PATH="$PWD/lib/blaze-3.8"
    - export CONDA_ENV_PATH="$PWD/miniconda3/envs/pommer_build"
    - export Torch_DIR="$PWD/lib/libtorch"
    # build
    - mkdir build
    - cd build
    - cmake -DUSE_TENSORRT=OFF -DUSE_TORCH=ON -DCMAKE_CXX_COMPILER="$(which g++)" ..
    - make VERBOSE=1 all
    - ./PommerLearn
  artifacts:
    paths:
      - ./build/PommerLearn
      - ./build/PommerLearnTest
      - ./build/libCrazyAra.so
      - ./build/libpomcpp.so
      - ./build/libPommerLearnPy.so

#run:
#  stage: test
#  needs: ["build"]
#  script:
#    - cd ./build
#    - ldd ./PommerLearn
#    - ./PommerLearn
